// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehxpcasdwxbpwxbtovgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoeHBjYXNkd3hicHd4YnRvdmd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzQzNTAsImV4cCI6MjA2MTY1MDM1MH0.N-AZDsQyTb5CN1ioCS0bG8if2aUTVowoMbl4af2wdJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);